project_id = "itoylenzvahbscgjgtqf"

[functions.dispatch-trial-emails]
verify_jwt = false

[functions.subscription-grace-cleanup]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.abacate-webhook]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.recovery-emails]
verify_jwt = false
