/**
 * Nome de gente pra módulo e aba (os ids que o module_analytics grava).
 * Rótulos tirados das próprias telas (TABS de cada página) — o que o cliente
 * vê. Aba desconhecida cai no id embelezado, nunca some.
 */

const MODULOS: Record<string, { emoji: string; nome: string }> = {
  financas: { emoji: "💰", nome: "Finanças" },
  rotina: { emoji: "📅", nome: "Rotina" },
  treino: { emoji: "💪", nome: "Treino" },
  dieta: { emoji: "🥗", nome: "Dieta" },
  saude: { emoji: "❤️", nome: "Saúde" },
  desenvolvimento: { emoji: "🎯", nome: "Metas" },
  hiperfoco: { emoji: "🧠", nome: "Foco" },
  estudos: { emoji: "📚", nome: "Estudos" },
  carreira: { emoji: "💼", nome: "Carreira" },
  biblioteca: { emoji: "📖", nome: "Leitura" },
  casa: { emoji: "🏠", nome: "Casa" },
  beleza: { emoji: "✨", nome: "Beleza" },
  viagens: { emoji: "✈️", nome: "Viagens" },
  relacionamentos: { emoji: "🤝", nome: "Relações" },
  pet: { emoji: "🐶", nome: "Pet" },
  detox: { emoji: "🚭", nome: "Detox" },
  conquistas: { emoji: "🏆", nome: "Conquistas" },
  home: { emoji: "🏡", nome: "Início" },
};

const ABAS: Record<string, string> = {
  "financas:dashboard": "Painel",
  "financas:financeiro": "Meu financeiro",
  "financas:investimentos": "Investimentos",
  "financas:itens": "Desejos",
  "financas:viagem": "Viagem",
  "financas:simuladores": "Simuladores",
  "financas:limites": "Limites",
  "financas:relatorios": "Relatórios",
  "financas:saude": "Saúde financeira",
  "rotina:semana": "Minha semana",
  "rotina:mes": "Meu mês",
  "rotina:diario": "Diário",
  "rotina:revisao": "Revisão",
  "rotina:foco": "Foco",
  "treino:hoje": "Hoje",
  "treino:semana": "Semana",
  "treino:evolucao": "Evolução",
  "treino:config": "Configurar",
  "treino:resumo": "Resumo",
  "treino:records": "Recordes",
  "treino:progressao": "Progressão",
  "dieta:cardapio": "Cardápio",
  "dieta:jejum": "Jejum",
  "dieta:receitas": "Receitas",
  "dieta:lista": "Lista",
  "dieta:diario": "Diário",
  "saude:hoje": "Hoje",
  "saude:evolucao": "Evolução",
  "saude:log": "Log médico",
  "desenvolvimento:sobre": "Sobre mim",
  "desenvolvimento:metas": "Metas",
  "desenvolvimento:diario": "Diário",
  "desenvolvimento:humor": "Humor e score",
  "desenvolvimento:respiracao": "Respiração",
  "desenvolvimento:gratidao": "Gratidão",
  "desenvolvimento:desafios": "Desafios",
  "desenvolvimento:carta": "Carta",
  "hiperfoco:dia": "Dia",
  "hiperfoco:busca": "Busca",
  "hiperfoco:metas": "Metas",
  "hiperfoco:estrategia": "Estratégia",
  "hiperfoco:timeline": "Linha do tempo",
  "hiperfoco:ideias": "Ideias",
  "hiperfoco:sonhos": "Sonhos",
  "estudos:estudos": "Estudos",
  "estudos:metodo": "Método",
  "estudos:grade": "Grade",
  "estudos:tarefas": "Tarefas",
  "estudos:caderno": "Caderno",
  "estudos:pomodoro": "Pomodoro",
  "carreira:dia": "Meu dia",
  "carreira:jobs": "Vagas",
  "carreira:portfolio": "Portfólio",
  "carreira:network": "Rede",
  "carreira:skills": "Habilidades",
  "carreira:interview": "Preparo p/ entrevista",
  "biblioteca:lendo": "Lendo",
  "biblioteca:quero-ler": "Quero ler",
  "biblioteca:lido": "Lidos",
  "biblioteca:abandonado": "Abandonados",
  "biblioteca:estante": "Estante",
  "biblioteca:desafio": "Desafio",
  "biblioteca:insights": "Insights",
  "biblioteca:emprestados": "Emprestados",
  "casa:comodos": "Cômodos",
  "casa:mercado": "Mercado",
  "casa:rotina": "Rotina",
  "casa:despensa": "Despensa",
  "casa:cardapio": "Cardápio",
  "casa:manutencao": "Manutenção",
  "casa:coop": "Co-op",
  "casa:seguranca": "Segurança",
  "casa:utilidades": "Utilidades",
  "beleza:routine": "Rotina",
  "beleza:shelf": "Bancada",
  "beleza:diary": "Diário",
  "viagens:destinos": "Destinos",
  "viagens:passeios": "Passeios",
  "viagens:cronograma": "Roteiro",
  "viagens:mala": "Mala",
  "viagens:budget": "Orçamento",
  "viagens:divisor": "Rachar conta",
  "viagens:lugares": "Lugares",
  "viagens:diario": "Diário",
  "viagens:moeda": "Câmbio",
  "viagens:seguranca": "SOS",
  "viagens:countdown": "Contagem",
  "relacionamentos:pessoas": "Pessoas",
  "relacionamentos:agenda": "Agenda",
  "relacionamentos:momentos": "Momentos",
  "relacionamentos:presentes": "Presentes",
  "relacionamentos:eventos": "Eventos",
  "pet:pets": "Pets",
  "pet:saude": "Saúde",
  "pet:rotina": "Rotina",
  "pet:gastos": "Gastos",
  "pet:diario": "Diário",
  "detox:rastreador": "Rastreador",
  "detox:diario": "Diário",
  "detox:conquistas": "Conquistas",
  "detox:stats": "Estatísticas",
};

export function embelezar(s: string): string {
  const t = s.replace(/[_-]+/g, " ").trim();
  return t ? t.charAt(0).toUpperCase() + t.slice(1) : s;
}

export const nomeModulo = (id: string): { emoji: string; nome: string } =>
  MODULOS[id] ?? { emoji: "•", nome: embelezar(id) };

export const nomeAba = (modulo: string, aba: string): string =>
  ABAS[`${modulo}:${aba}`] ?? (aba ? embelezar(aba) : "(sem aba)");

/** Chave de card vem em CAIXA ALTA sem acento ("COMO VOCE ESTA HOJE"). */
export const nomeCard = (card: string): string =>
  card && card !== "?" ? card.charAt(0) + card.slice(1).toLowerCase() : "(sem título)";
